IBM/event-streams

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/issue.md
Signed-off-by: Gavin Royce Quadros <gavin.r.quadros@ibm.com>
> Adding issue templates

- support/get-logs.sh
This commit updates the get-logs.sh script to also retrieve the
replicator pod logs.
Signed-off-by: Andrew Borley <borley@uk.ibm.com>
> Collect logs for replicator pods

- support/get-logs.sh
Require the user to specify the namespace that ES
is deployed in, and the release name of it
Contributes to: mhub/qp-planning#4518
Signed-off-by: Tom Jefferson <thomas.jefferson1@ibm.com>
> feat: Require ns and release

- support/get-logs.sh
Improvements to error handling etc.
Signed-off-by: Tom Aley <thomas.aley@ibm.com>
> feat: ReWrite get-logs

- support/get-logs.sh
- Tarball name issue fix (remove colons)
- Minor print formatting tweaks
- Wrap helm presence command
Signed-off-by: Tom Aley <thomas.aley@ibm.com>
> fix: Small issue fixes

- support/get-logs.sh
```
Check auth pods in kube-system
Run kubectl top commands
Signed-off-by: Dave <davilane@uk.ibm.com>
```
> feat: update get-logs.sh to 2020.1.1

- support/get-logs.sh
updates to get helm values and storage class details.
Signed-off-by: Gavin Royce Quadros <gavin.r.quadros@ibm.com>
> chore: get helm values

- support/dashboards/kibana/Event Streams Kibana Dashboards.json
- support/dashboards/kibana/readMe.md
Added various Kibana Dashboards which can be imported
into the customer system to monitor various logs.
Signed-off-by: Julian Goh <julian.goh@ibm.com>
> feat: Add Kibana Dashboards

- support/dashboards/kibana/Event Streams Kibana Dashboards.json
- support/dashboards/kibana/readMe.md
Add Kafka brokers dashboard which will help to determine
whether Kafka's can communicate with another.
Signed-off-by: Julian Goh <julian.goh@ibm.com>
> feat: Add Kafka brokers dashboard

- support/get-logs.sh
update get logs to be:
1) more consistent - use the same syntax consistently
with regards to arrays quotes {} etc.
2) more readable - move more functionality especially
some of the more unique pieces into functions so they
can be more easily used in the future. And separate
pieces of the code by it's goal
3) more extensible - rework some of the more hardcoded
pieces to be more extensible so they can be easily
made to work with future changes
4) more openshift - add support for pieces that were
broken / missing in openshift e.g. routes and dns / etcd
Contributes to: mhub/qp-planning#5638
Signed-off-by: Chris Patmore <christopher.patmore@ibm.com>
> 5638 update get logs

- support/get-logs.sh
update the get logs script to support the operator
release
Contributes to: mhub/qp-planning#5638
Signed-off-by: Chris Patmore <christopher.patmore@ibm.com>
> feat: update get-logs to support operator

- support/get-logs.sh
add connection tests from Zk to ZK and from
kafka to ZK
Contributes to: mhub/qp-planning#5616
Signed-off-by: Chris Patmore <christopher.patmore@ibm.com>
> feat: add connection tests for ZK

- _10.0/04-security/01-managing-access.md
- _10.0/05-replication/02-planning-replication.md
- _10.0/05-replication/05-replication-failover.md
- _10.0/08-troubleshooting/30-default-scc-issues.md
Preparing failover updates, and minor enhancmenets to managing access and SCC troubleshoooting.
> Expanding failover information and a couple of enhancements

- support/get-logs.sh
This commit adds a check of the release name
by getting a list of pods using the release
name as a label selector. If we get an error
message returned, then we fail the script as the
release name is wrong or not valid for the
namespace.
It also adds a check of all secrets in the
namespace, as not all secrets ES uses have
release labels associated with them.
We also get the tls.cluster cert which is the
Common Services CA Cert.
Contributes to: mhub/qp-planning#200
Signed-off-by: Tim Mitchell <tim_mitchell@uk.ibm.com>
> feat: Add Release name check to get logs

- _11.0/02-installing/01-prereqs.md
- _11.0/02-installing/05-installing.md
- _11.0/02-installing/07-configuring.md
signed off by: gabort@uk.ibm.com
> Minor adjustments

- _10.5/08-troubleshooting/43-common-services-320-blocks-upgrade.md
- _11.0/04-schemas/04-setting-java-apps-to-use-schemas.md
- _11.0/04-schemas/06-migrating-to-registry.md
- _11.0/04-schemas/08-setting-java-apps-to-use-apicurio-serdes.md
- _11.0/08-troubleshooting/46-common-services-320-blocks-upgrade.md
- _data/navigation.yml
Signed-off-by: gabort@uk.ibm.com
> 8049 and 8635 publish

- _tutorials/kafka-streams.md
Signed off by: Gabor Tangelmayer gabort@uk.ibm.com
> Fixing link

- _connectors/kc-sink-filestream/Licensing and support.md
- _connectors/kc-sink-filestream/index.md
- _connectors/kc-sink-filestream/installation.md
- _connectors/kc-source-filestream/Licensing and support.md
- _connectors/kc-source-filestream/index.md
- _connectors/kc-source-filestream/installation.md
Signed off by: Vignesh Kumar Elumalai <vigneshkumar.elumalai@ibm.com>
> Typo - FileStream Connectors

- _11.1/08-troubleshooting/49-missing-crds-block-upgrade.md
- _data/navigation.yml
Signed by: Vignesh Kumar Elumalai <vigneshkumar.elumalai@ibm.com>
> Adding TS for 11.1.5 CRD issue

- _11.1/01-about/01-whats-new.md
Whats new update: apicurio link didnt work. 
Signed off by: Vignesh Kumar Elumalai <vigneshkumar.elumalai@ibm.com>
> tweaks to homepage

- _11.0/02-installing/07-configuring.md
- _11.1/02-installing/07-configuring.md
Signed off by: Vignesh Kumar Elumalai <vigneshkumar.elumalai@ibm.com>
> spelling change

- _11.1/02-installing/06-installing.md
> Add Gabor's suggestion on HA

- _11.0/07-administering/02-cluster-health.md
- _11.1/07-administering/02-cluster-health.md
- _11.2/07-administering/02-cluster-health.md
> Typo create

- _11.2/08-troubleshooting/02-gathering-logs.md
> Revert image address for gathering logs

- _11.2/02-installing/08-postinstallation.md
> Remove duplicate content in Post installation

- _layouts/redirects.html
> Update time for redirects

- _layouts/redirects.html
This resolves the issue of always taking it to the homepage. 
> Address redirects

- _layouts/redirects.html
common pages like connectors, api, support was going to the homepage. This resolves that.
> address redirects 2
